name: "Build RFC index"
description: "Builds an index from the IETF RFC mini-index. Outputs an index JSON file and optionally downloads the RFC documents in HTML format."
inputs:
  download-path:
    description: "Path to download RFC documents to. Optional, will not download if not set."
    required: true
    default: "./site/doc"
  index-file-path:
    description: "Path to generated index JSON"
    required: true
    default: "./site/index.json"
outputs:
  index-file-path:
    description: "Path to the generated index JSON"

runs:
  using: "docker"
  image: "../../../index-builder.dockerfile"
  args:
    - ${{ inputs.download-path }}
    - ${{ inputs.index-file-path }}
