name: github pages
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 4 2 * *'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build RFC index
        uses: ./.github/actions/build-rfc-index
        with:
          download-path: ./site/
          index-file-path: ./site/index.json

      - name: List publish dir contents
        run: ls -la ./site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
          cname: hummus.rb9.nl
