name: github pages
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ./.github/actions/build-rfc-index
        with:
          download-path: ./src/site/rfcs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/site
